# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-13 18:47
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obsdate', models.DateField(default=datetime.date.today, verbose_name='Date of Observation')),
                ('count', models.IntegerField(verbose_name='Flock Count')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Location')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('last_modify_date', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
                ('user_create', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
